name: Backend Docker Build

on:
  push:
    paths:
      - 'Backend/**'
      - '.github/workflows/backend-build.yml'
    branches:
      - main
      - sneha_dockercontainer_branch
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout backend code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Backend Docker Image
        run: |
          docker build -t team-implant/implant-backend:latest ./Backend/DotNetSQL
