name: Frontend Docker Build

on:
  push:
    paths:
      - 'Frontend/**'
      - '.github/workflows/frontend-build.yml'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout frontend code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Frontend Docker Image
        run: |
          docker build -t team-implant/implant-frontend:latest ./Frontend
