version: "3.8"

services:
  backend:
    image: ${DOCKER_REGISTRY:-team-implant}/implant-backend:${TAG:-latest}
    build:
      context: ./Backend/DotNetSQL
      dockerfile: Dockerfile
    container_name: implant_backend
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - implant-network

  frontend:
    image: ${DOCKER_REGISTRY:-team-implant}/implant-frontend:${TAG:-latest}
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: implant_frontend
    depends_on:
      - backend
      - mlservice
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://backend:80
      - REACT_APP_ML_API_URL=http://mlservice:5000
    networks:
      - implant-network

  mlservice:
    image: ${DOCKER_REGISTRY:-team-implant}/implant-mlservice:${TAG:-latest}
    build:
      context: ./Backend/MLService
      dockerfile: Dockerfile
    container_name: implant_mlservice
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=development
    networks:
      - implant-network

networks:
  implant-network:
    driver: bridge