name: imPlant CI/CD Pipeline
on:
  push:
    branches: [ main, master, develop, DEV_Backend ]
  pull_request:
    branches: [ main, master, develop ]
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    # Build and push standard Backend
    - name: Build and push Backend
      uses: docker/build-push-action@v4
      with:
        context: ./Backend/DotNetSQL
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/implant/implant-backend:latest
        no-cache: true
    
    # Build and push Backend ARM64
    - name: Build and push Backend (ARM64)
      uses: docker/build-push-action@v4
      with:
        context: ./Backend/DotNetSQL
        file: ./Backend/DotNetSQL/Dockerfile.arm64
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/implant/implant-backend-arm64:latest
        platforms: linux/arm64
        no-cache: true
    
    # Build and push IoT Server ARM64
    - name: Build and push IoT Server (ARM64)
      uses: docker/build-push-action@v4
      with:
        context: ./IoT/IoT_server/TcpGrpcBridgeServer
        file: ./IoT/IoT_server/TcpGrpcBridgeServer/Dockerfile.arm64
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/implant/iot-server-arm64:latest
        platforms: linux/arm64
        no-cache: true
    
    # Build and push MLService
    - name: Build and push MLService
      uses: docker/build-push-action@v4
      with:
        context: ./Backend/MLService
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/implant/implant-mlservice:latest
        no-cache: true
        
    # Build and push Frontend
    - name: Build and push Frontend
      uses: docker/build-push-action@v4
      with:
        context: ./Frontend
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/implant/implant-frontend:latest
        no-cache: true