name: imPlant CI/CD Pipeline for Google Cloud Platform

on:
  push:
    branches: [ main, DEV_Backend ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          9.0.x

    - name: Build Backend
      run: |
        # Create a modified Dockerfile that skips the build step
        cd ./Backend/DotNetSQL
        
        # Build on the GitHub runner
        dotnet publish DotNetSQL.csproj -c Release -o ./backend/publish
        
        # Create a dockerfile that just copies the pre-built files
        cat > Dockerfile.armcopy << EOF
        FROM mcr.microsoft.com/dotnet/aspnet:9.0
        WORKDIR /app
        COPY ./backend/publish/ .
        EXPOSE 8080
        ENTRYPOINT ["dotnet", "DotNetSQL.dll"]
        EOF
        
        # Let Docker build using the pre-built files
        docker buildx build --platform linux/arm64,linux/amd64 -f Dockerfile.armcopy -t ghcr.io/${{ github.repository_owner }}/implant/implant-backend-universal:latest --push .

    - name: Build IoT Server
      run: |
        # Create a modified Dockerfile that skips the build step
        cd ./IoT/IoT_server/TcpGrpcBridgeServer
        
        # Build on the GitHub runner
        dotnet publish TcpGrpcBridgeServer.csproj -c Release -o ./iot/publish
        
        # Create a dockerfile that just copies the pre-built files
        cat > Dockerfile.armcopy << EOF
        FROM mcr.microsoft.com/dotnet/aspnet:9.0
        WORKDIR /app
        COPY ./iot/publish/ .
        EXPOSE 5000 23
        ENTRYPOINT ["dotnet", "TcpGrpcBridgeServer.dll"]
        EOF
        
        # Let Docker build using the pre-built files
        docker buildx build --platform linux/arm64,linux/amd64 -f Dockerfile.armcopy -t ghcr.io/${{ github.repository_owner }}/implant/iot-server-universal:latest --push .
