name: Build and deploy ASP.Net Core app to Azure Web App - sep4-implant

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Restore dependencies
        run: dotnet restore Backend/DotNetSQL/DotNetSQL.csproj

      - name: Build project
        run: dotnet build Backend/DotNetSQL/DotNetSQL.csproj --configuration Release --no-restore

      - name: Publish project
        run: dotnet publish Backend/DotNetSQL/DotNetSQL.csproj --configuration Release --output ./publish

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-app
          path: ./publish

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: dotnet-app
          path: ./publish

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_854AB0579A5941F7815014C3AC91BA7F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1B4B735F36ED4037B4A474B8B34DCDEC }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_597B9FA1D94647769C4FCF5B653D4B3E }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'sep4-implant'
          slot-name: 'Production'
          package: ./publish
